eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8081
spring:
  application:
    name: hm-back
  thymeleaf:
    cache: false
    prefix: classpath:templates
    suffix: .html
    mode: HTML
feign:
  hystrix:
    #开启feign熔断器
    enabled: true
